# Generated by Django 4.0.6 on 2022-08-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_roll', models.IntegerField()),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('pe_phone', models.IntegerField()),
                ('pe_wphone', models.IntegerField()),
                ('pr_phone', models.IntegerField()),
                ('pr_wphone', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Gender', models.BooleanField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('pdis', models.BooleanField()),
                ('address', models.CharField(max_length=100)),
                ('AT_post', models.CharField(max_length=100)),
                ('Tal', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('is_sameadd', models.BooleanField()),
                ('address2', models.CharField(max_length=100)),
                ('AT_post2', models.CharField(max_length=100)),
                ('Tal2', models.CharField(max_length=100)),
                ('district2', models.CharField(max_length=100)),
                ('pin_code2', models.IntegerField()),
                ('Religion', models.CharField(max_length=100)),
                ('Categore', models.CharField(max_length=100)),
                ('is_fatheralive', models.BooleanField()),
                ('is_motheralive', models.BooleanField()),
                ('father_occ', models.CharField(max_length=100)),
                ('mother_occ', models.CharField(max_length=100)),
                ('Family_inc', models.IntegerField()),
                ('par_res', models.CharField(max_length=100)),
                ('SSC_res', models.IntegerField()),
                ('SSC_year', models.IntegerField()),
                ('HSC_res', models.IntegerField()),
                ('HSC_year', models.IntegerField()),
                ('NOther_cor', models.CharField(max_length=100)),
                ('FY_addYear', models.IntegerField()),
                ('SY_addYear', models.IntegerField()),
                ('TY_addYear', models.IntegerField()),
                ('Sem1_res', models.IntegerField()),
                ('sem1_back', models.CharField(max_length=100)),
                ('sem1pass_ex', models.CharField(max_length=100)),
                ('Sem2_res', models.IntegerField()),
                ('sem2_back', models.CharField(max_length=100)),
                ('sem2pass_ex', models.CharField(max_length=100)),
                ('Sem3_res', models.IntegerField()),
                ('sem3_back', models.CharField(max_length=100)),
                ('sem3pass_ex', models.CharField(max_length=100)),
                ('Sem4_res', models.IntegerField()),
                ('sem4_back', models.CharField(max_length=100)),
                ('sem4pass_ex', models.CharField(max_length=100)),
                ('Sem5_res', models.IntegerField()),
                ('sem5_back', models.CharField(max_length=100)),
                ('sem5pass_ex', models.CharField(max_length=100)),
                ('Sem6_res', models.IntegerField()),
                ('sem6_back', models.CharField(max_length=100)),
                ('sem6pass_ex', models.CharField(max_length=100)),
                ('photo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_roll', models.IntegerField()),
                ('Gendar', models.BooleanField()),
                ('BOD', models.DateField()),
            ],
        ),
    ]
